language: go

go:
  - "1.11"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - env GO111MODULE=on go get -t -v ./...
  - env GO111MODULE=on go test -v ./... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken eBfZq7Qhdsnxz8dsVjxsUhYSSiY2POKIB
